package com.app.docmgr.model;

import java.util.*;




/**
 * Announcement generated by hbm2java
 */
public class Announcement  implements java.io.Serializable {

    // Fields    

     private Long id;
     private String content;
     private Lookup announcementType;
     private String subject;
     private String targetUsers;
     private String targetOrganizations;
     private Date createdDate;
     private String createdBy;
     private Date lastUpdatedDate;
     private String lastUpdatedBy;
     private Status status;


    // Constructors

    /** default constructor */
    public Announcement() {
    }
    
    /** constructor with id */
    public Announcement(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 
     */
    public Lookup getAnnouncementType() {
        return this.announcementType;
    }
    
    public void setAnnouncementType(Lookup announcementType) {
        this.announcementType = announcementType;
    }

    /**
     * 
     */
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * 
     */
    public String getTargetUsers() {
        return this.targetUsers;
    }
    
    public void setTargetUsers(String targetUsers) {
        this.targetUsers = targetUsers;
    }

    /**
     * 
     */
    public String getTargetOrganizations() {
        return this.targetOrganizations;
    }
    
    public void setTargetOrganizations(String targetOrganizations) {
        this.targetOrganizations = targetOrganizations;
    }

    /**
     * 
     */
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * 
     */
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * 
     */
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * 
     */
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * 
     */
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }




}