package com.app.docmgr.model;

import java.util.*;




/**
 * AuditTrail generated by hbm2java
 */
public class AuditTrail  implements java.io.Serializable {

    // Fields    

     private Long id;
     private Date auditTime;
     private String entity;
     private String doneBy;
     private String sessionId;
     private String approvedBy;
     private String actions;
     private String description;


    // Constructors

    /** default constructor */
    public AuditTrail() {
    }
    
    /** constructor with id */
    public AuditTrail(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public Date getAuditTime() {
        return this.auditTime;
    }
    
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * 
     */
    public String getEntity() {
        return this.entity;
    }
    
    public void setEntity(String entity) {
        this.entity = entity;
    }

    /**
     * 
     */
    public String getDoneBy() {
        return this.doneBy;
    }
    
    public void setDoneBy(String doneBy) {
        this.doneBy = doneBy;
    }

    /**
     * 
     */
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * 
     */
    public String getApprovedBy() {
        return this.approvedBy;
    }
    
    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }

    /**
     * 
     */
    public String getActions() {
        return this.actions;
    }
    
    public void setActions(String actions) {
        this.actions = actions;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}