package com.app.docmgr.model;

import java.util.*;




/**
 * Bookmark generated by hbm2java
 */
public class Bookmark  implements java.io.Serializable {

    // Fields    

     private Long id;
     private String url;
     private String name;
     private String note;
     private Lookup bookmarkType;
     private Date createdDate;
     private String createdBy;
     private Status status;
     private User owner;


    // Constructors

    /** default constructor */
    public Bookmark() {
    }
    
    /** constructor with id */
    public Bookmark(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * 
     */
    public Lookup getBookmarkType() {
        return this.bookmarkType;
    }
    
    public void setBookmarkType(Lookup bookmarkType) {
        this.bookmarkType = bookmarkType;
    }

    /**
     * 
     */
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * 
     */
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * 
     */
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * 
     */
    public User getOwner() {
        return this.owner;
    }
    
    public void setOwner(User owner) {
        this.owner = owner;
    }




}