package com.app.docmgr.model;

import java.util.*;




/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {

    // Fields    

     private Long id;
     private String name;
     private String documentType;
     private String contentType;
     private String documentNumber;
     private String repositoryId;
     private String documentVersion;
     private String description;
     private Lookup securityLevel;
     private Status status;
     private Date createdDate;
     private String createdBy;
     private Date lastUpdatedDate;
     private String lastUpdatedBy;
     private Folder parentFolder;
     private Document parentDocument;


    // Constructors

    /** default constructor */
    public Document() {
    }
    
    /** constructor with id */
    public Document(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    /**
     * 
     */
    public String getContentType() {
        return this.contentType;
    }
    
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * 
     */
    public String getDocumentNumber() {
        return this.documentNumber;
    }
    
    public void setDocumentNumber(String documentNumber) {
        this.documentNumber = documentNumber;
    }

    /**
     * 
     */
    public String getRepositoryId() {
        return this.repositoryId;
    }
    
    public void setRepositoryId(String repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * 
     */
    public String getDocumentVersion() {
        return this.documentVersion;
    }
    
    public void setDocumentVersion(String documentVersion) {
        this.documentVersion = documentVersion;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 
     */
    public Lookup getSecurityLevel() {
        return this.securityLevel;
    }
    
    public void setSecurityLevel(Lookup securityLevel) {
        this.securityLevel = securityLevel;
    }

    /**
     * 
     */
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * 
     */
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * 
     */
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * 
     */
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * 
     */
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * 
     */
    public Folder getParentFolder() {
        return this.parentFolder;
    }
    
    public void setParentFolder(Folder parentFolder) {
        this.parentFolder = parentFolder;
    }

    /**
     * 
     */
    public Document getParentDocument() {
        return this.parentDocument;
    }
    
    public void setParentDocument(Document parentDocument) {
        this.parentDocument = parentDocument;
    }




}