package com.app.docmgr.model;

import java.util.*;




/**
 * EmailLog generated by hbm2java
 */
public class EmailLog  implements java.io.Serializable {

    // Fields    

     private Long id;
     private String type;
     private String sender;
     private String rcptTo;
     private String subject;
     private String message;
     private Integer retry;
     private Status status;
     private Date dueDate;
     private Date sentDate;
     private Date lastTrialDate;


    // Constructors

    /** default constructor */
    public EmailLog() {
    }
    
    /** constructor with id */
    public EmailLog(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    /**
     * 
     */
    public String getSender() {
        return this.sender;
    }
    
    public void setSender(String sender) {
        this.sender = sender;
    }

    /**
     * 
     */
    public String getRcptTo() {
        return this.rcptTo;
    }
    
    public void setRcptTo(String rcptTo) {
        this.rcptTo = rcptTo;
    }

    /**
     * 
     */
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * 
     */
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * 
     */
    public Integer getRetry() {
        return this.retry;
    }
    
    public void setRetry(Integer retry) {
        this.retry = retry;
    }

    /**
     * 
     */
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * 
     */
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * 
     */
    public Date getSentDate() {
        return this.sentDate;
    }
    
    public void setSentDate(Date sentDate) {
        this.sentDate = sentDate;
    }

    /**
     * 
     */
    public Date getLastTrialDate() {
        return this.lastTrialDate;
    }
    
    public void setLastTrialDate(Date lastTrialDate) {
        this.lastTrialDate = lastTrialDate;
    }




}