package com.app.docmgr.model;

import java.util.*;




/**
 * Forum generated by hbm2java
 */
public class Forum  implements java.io.Serializable {

    // Fields    

     private Long id;
     private String code;
     private String icon;
     private String name;
     private Lookup forumType;
     private String address;
     private Date createdDate;
     private String createdBy;
     private Date lastUpdatedDate;
     private String lastUpdatedBy;
     private String filterCode;
     private Forum parentForum;


    // Constructors

    /** default constructor */
    public Forum() {
    }
    
    /** constructor with id */
    public Forum(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 
     */
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public Lookup getForumType() {
        return this.forumType;
    }
    
    public void setForumType(Lookup forumType) {
        this.forumType = forumType;
    }

    /**
     * 
     */
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * 
     */
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * 
     */
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * 
     */
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * 
     */
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * 
     */
    public String getFilterCode() {
        return this.filterCode;
    }
    
    public void setFilterCode(String filterCode) {
        this.filterCode = filterCode;
    }

    /**
     * 
     */
    public Forum getParentForum() {
        return this.parentForum;
    }
    
    public void setParentForum(Forum parentForum) {
        this.parentForum = parentForum;
    }




}