package com.app.docmgr.model;

import java.util.*;




/**
 * GenericReport generated by hbm2java
 */
public class GenericReport  implements java.io.Serializable {

    // Fields    

     private Long id;
     private String name;
     private String reportFields;
     private String searchFields;
     private String reportSql;
     private String description;
     private String columnAction;
     private Status status;


    // Constructors

    /** default constructor */
    public GenericReport() {
    }
    
    /** constructor with id */
    public GenericReport(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getReportFields() {
        return this.reportFields;
    }
    
    public void setReportFields(String reportFields) {
        this.reportFields = reportFields;
    }

    /**
     * 
     */
    public String getSearchFields() {
        return this.searchFields;
    }
    
    public void setSearchFields(String searchFields) {
        this.searchFields = searchFields;
    }

    /**
     * 
     */
    public String getReportSql() {
        return this.reportSql;
    }
    
    public void setReportSql(String reportSql) {
        this.reportSql = reportSql;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 
     */
    public String getColumnAction() {
        return this.columnAction;
    }
    
    public void setColumnAction(String columnAction) {
        this.columnAction = columnAction;
    }

    /**
     * 
     */
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }




}