package com.app.docmgr.model;

import java.util.*;




/**
 * IPassportPool generated by hbm2java
 */
public class IPassportPool  implements java.io.Serializable {

    // Fields    

     private Long id;
     private String ipassport;
     private String loginId;
     private Date lastLogin;
     private Date lastActive;


    // Constructors

    /** default constructor */
    public IPassportPool() {
    }
    
    /** constructor with id */
    public IPassportPool(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getIpassport() {
        return this.ipassport;
    }
    
    public void setIpassport(String ipassport) {
        this.ipassport = ipassport;
    }

    /**
     * 
     */
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * 
     */
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * 
     */
    public Date getLastActive() {
        return this.lastActive;
    }
    
    public void setLastActive(Date lastActive) {
        this.lastActive = lastActive;
    }




}