package com.app.docmgr.model;

import java.util.*;




/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {

    // Fields    

     private Long id;
     private String name;
     private String vgroup;
     private String description;


    // Constructors

    /** default constructor */
    public Privilege() {
    }
    
    /** constructor with id */
    public Privilege(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getVgroup() {
        return this.vgroup;
    }
    
    public void setVgroup(String vgroup) {
        this.vgroup = vgroup;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}