package com.app.docmgr.model;

import java.util.*;




/**
 * SharedDocument generated by hbm2java
 */
public class SharedDocument  implements java.io.Serializable {

    // Fields    

     private Long id;
     private Document document;
     private User user;
     private String grantAction;
     private Status status;
     private Date createdDate;
     private String createdBy;


    // Constructors

    /** default constructor */
    public SharedDocument() {
    }
    
    /** constructor with id */
    public SharedDocument(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }

    /**
     * 
     */
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * 
     */
    public String getGrantAction() {
        return this.grantAction;
    }
    
    public void setGrantAction(String grantAction) {
        this.grantAction = grantAction;
    }

    /**
     * 
     */
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * 
     */
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * 
     */
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}