package com.app.docmgr.model;

import java.util.*;




/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {

    // Fields    

     private Long id;
     private String type;
     private String code;
     private String state;
     private String name;
     private String description;


    // Constructors

    /** default constructor */
    public Status() {
    }
    
    /** constructor with id */
    public Status(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    /**
     * 
     */
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 
     */
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}