package com.app.docmgr.model;

import java.util.*;




/**
 * SystemSequence generated by hbm2java
 */
public class SystemSequence  implements java.io.Serializable {

    // Fields    

     private Long id;
     private String type;
     private String param;
     private Long sequence;


    // Constructors

    /** default constructor */
    public SystemSequence() {
    }
    
    /** constructor with id */
    public SystemSequence(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    /**
     * 
     */
    public String getParam() {
        return this.param;
    }
    
    public void setParam(String param) {
        this.param = param;
    }

    /**
     * 
     */
    public Long getSequence() {
        return this.sequence;
    }
    
    public void setSequence(Long sequence) {
        this.sequence = sequence;
    }




}